name:                orhle
version:             0.1.0.0
github:              "rcdickerson/rhle-verifier"
author:              "Rob Dickerson"
maintainer:          "rc.dickerson@gmail.com"
copyright:           "Rob Dickerson"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/rcdickerson/rhle-verifier#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- ceili
- containers
- lrucache
- mtl
- parsec
- prettyprinter
- random
- simple-smt
- smtLib
- split
- text
- transformers
- unbounded-delays
- uuid

library:
  source-dirs:
    - src
  exposed-modules:
    - Orhle
    - Orhle.CInvGen
    - Orhle.CValue
    - Orhle.CVInvGen
    - Orhle.DTInvGen
    - Orhle.DTLearn
    - Orhle.OrhleParser
    - Orhle.RelationalPTS
    - Orhle.SpecImp
    - Orhle.StepStrategy
    - Orhle.Triple

executables:
  orhle-exe:
    main:                Main.hs
    source-dirs:         app-orhle
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - orhle
    - prettyprinter

tests:
  orhle-test:
    main:                TestMain.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - directory
    - fast-logger
    - filepath
    - orhle
    - HTF
