name:                orhle
version:             0.1.0.0
github:              "rcdickerson/rhle-verifier"
author:              "Rob Dickerson"
maintainer:          "rc.dickerson@gmail.com"
copyright:           "Rob Dickerson"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/rcdickerson/rhle-verifier#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- mtl
- parsec
- pretty
- prettyprinter
- simple-smt
- smtLib
- split
- text
- transformers
- unbounded-delays

library:
  source-dirs:
    - src
  exposed-modules:
    - Orhle
    - Orhle.Assertion
    - Orhle.Imp

executables:
  orhle-exe:
    main:                Main.hs
    source-dirs:         app-orhle
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - orhle
    - pretty-show
  java-orhle-exe:
    main:                Main.hs
    source-dirs:         app-java
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - orhle
    - language-java
    - filepath

tests:
  orhle-test:
    main:                Main.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - directory
    - filepath
    - orhle
    - HUnit
